2020-11-04 21:04:16,052 INFO root Loading cache from /media/compute/homes/aharter/.cache/phyre/offline_simulation/100000/ball
2020-11-04 21:04:22,913 INFO __main__ VS-uni-mean ball_within_template 0 || loading data for generative training...
2020-11-04 21:06:04,027 INFO __main__ VS-uni-mean ball_within_template 0 || training 'generative' models...
2020-11-04 21:06:06,815 INFO root training epoch 1...
2020-11-04 21:06:36,210 INFO root collecting auccess after epoch 1...
2020-11-04 21:06:43,490 INFO root Loading cache from /media/compute/homes/aharter/.cache/phyre/offline_simulation/100000/ball
2020-11-04 21:06:45,166 ERROR __main__ Exception occured:
Traceback (most recent call last):
  File "solver.py", line 261, in <module>
    solver.train_supervised(epochs=epochs, train_mode=train_mode, test_ids = test_ids, setup=f'{eval_setup}_{fold_id}')
  File "/media/compute/homes/aharter/isy2020/phyre/flownet.py", line 1963, in train_supervised
    auccess = self.generative_auccess(test_ids, setup)
  File "/media/compute/homes/aharter/isy2020/phyre/flownet.py", line 897, in generative_auccess
    if self.radmode=="old":
AttributeError: 'FlownetSolver' object has no attribute 'radmode'
2020-11-04 21:20:58,844 INFO root Loading cache from /media/compute/homes/aharter/.cache/phyre/offline_simulation/100000/ball
2020-11-04 21:21:07,514 INFO __main__ VS-uni-mean ball_within_template 0 || loading data for generative training...
2020-11-04 21:22:51,638 INFO __main__ VS-uni-mean ball_within_template 0 || training 'generative' models...
2020-11-04 21:22:54,714 INFO root training epoch 1...
2020-11-04 21:23:26,237 INFO root collecting auccess after epoch 1...
2020-11-04 21:23:33,110 INFO root Loading cache from /media/compute/homes/aharter/.cache/phyre/offline_simulation/100000/ball
2020-11-04 21:23:34,811 ERROR __main__ Exception occured:
Traceback (most recent call last):
  File "solver.py", line 261, in <module>
    solver.train_supervised(epochs=epochs, train_mode=train_mode, test_ids = test_ids, setup=f'{eval_setup}_{fold_id}')
  File "/media/compute/homes/aharter/isy2020/phyre/flownet.py", line 1963, in train_supervised
    auccess = self.generative_auccess(test_ids, setup)
  File "/media/compute/homes/aharter/isy2020/phyre/flownet.py", line 897, in generative_auccess
    if self.radmode=="old":
AttributeError: 'FlownetSolver' object has no attribute 'radmode'
2020-11-04 22:15:16,614 INFO root Loading cache from /media/compute/homes/aharter/.cache/phyre/offline_simulation/100000/ball
2020-11-04 22:15:24,265 INFO __main__ VS-uni-mean ball_within_template 0 || loading data for generative training...
2020-11-04 22:17:05,476 INFO __main__ VS-uni-mean ball_within_template 0 || training 'generative' models...
2020-11-04 22:17:08,493 INFO root training epoch 1...
2020-11-04 22:17:43,455 INFO root collecting auccess after epoch 1...
2020-11-04 22:17:50,315 INFO root Loading cache from /media/compute/homes/aharter/.cache/phyre/offline_simulation/100000/ball
2020-11-04 22:17:52,073 ERROR __main__ Exception occured:
Traceback (most recent call last):
  File "solver.py", line 261, in <module>
    solver.train_supervised(epochs=epochs, train_mode=train_mode, test_ids = test_ids, setup=f'{eval_setup}_{fold_id}')
  File "/media/compute/homes/aharter/isy2020/phyre/flownet.py", line 1965, in train_supervised
    auccess = self.generative_auccess(test_ids, setup)
  File "/media/compute/homes/aharter/isy2020/phyre/flownet.py", line 907, in generative_auccess
    a  = sample_action_vector(ball, self.cache, uniform=self.uniform, radmode=self.radmode, mask=mask, check_border=True)
NameError: name 'sample_action_vector' is not defined
2020-11-04 22:30:16,500 INFO root Loading cache from /media/compute/homes/aharter/.cache/phyre/offline_simulation/100000/ball
2020-11-04 22:30:23,413 INFO __main__ VS-uni-mean ball_within_template 0 || loading data for generative training...
2020-11-04 22:32:06,667 INFO __main__ VS-uni-mean ball_within_template 0 || training 'generative' models...
2020-11-04 22:32:09,462 INFO root training epoch 1...
2020-11-04 22:32:39,772 INFO root collecting auccess after epoch 1...
2020-11-04 22:32:47,001 INFO root Loading cache from /media/compute/homes/aharter/.cache/phyre/offline_simulation/100000/ball
2020-11-04 22:32:48,727 ERROR __main__ Exception occured:
Traceback (most recent call last):
  File "solver.py", line 261, in <module>
    solver.train_supervised(epochs=epochs, train_mode=train_mode, test_ids = test_ids, setup=f'{eval_setup}_{fold_id}')
  File "/media/compute/homes/aharter/isy2020/phyre/flownet.py", line 1965, in train_supervised
    auccess = self.generative_auccess(test_ids, setup)
  File "/media/compute/homes/aharter/isy2020/phyre/flownet.py", line 907, in generative_auccess
    a  = sample_action_vector(ball, self.cache, uniform=self.uniform, radmode=self.radmode, mask=mask, check_border=True)
  File "/media/compute/homes/aharter/isy2020/phyre/phyre_utils.py", line 587, in sample_action_vector
    rad = rads.sorted(k=lambda x: x[1], descending=True)[0]
AttributeError: 'list' object has no attribute 'sorted'
2020-11-05 00:46:05,338 INFO root Loading cache from /media/compute/homes/aharter/.cache/phyre/offline_simulation/100000/ball
2020-11-05 00:46:09,621 INFO __main__ VS-uni-mean ball_within_template 0 || loading data for generative training...
2020-11-05 00:47:23,634 INFO __main__ VS-uni-mean ball_within_template 0 || training 'generative' models...
2020-11-05 00:47:32,328 INFO root training epoch 1...
2020-11-05 00:47:53,602 INFO root collecting auccess after epoch 1...
2020-11-05 00:47:58,905 INFO root Loading cache from /media/compute/homes/aharter/.cache/phyre/offline_simulation/100000/ball
2020-11-05 00:48:00,069 ERROR __main__ Exception occured:
Traceback (most recent call last):
  File "solver.py", line 261, in <module>
    solver.train_supervised(epochs=epochs, train_mode=train_mode, test_ids = test_ids, setup=f'{eval_setup}_{fold_id}')
  File "/media/compute/homes/aharter/isy2020/phyre/flownet.py", line 1965, in train_supervised
    auccess = self.generative_auccess(test_ids, setup)
  File "/media/compute/homes/aharter/isy2020/phyre/flownet.py", line 907, in generative_auccess
    a  = sample_action_vector(ball, self.cache, uniform=self.uniform, radmode=self.radmode, mask=mask, check_border=True)
  File "/media/compute/homes/aharter/isy2020/phyre/phyre_utils.py", line 587, in sample_action_vector
    rad = rads.sorted(k=lambda x: x[1], descending=True)[0]
AttributeError: 'list' object has no attribute 'sorted'
2020-11-05 09:11:41,761 INFO root Loading cache from /media/compute/homes/aharter/.cache/phyre/offline_simulation/100000/ball
2020-11-05 09:11:45,988 INFO __main__ VS-uni-mean ball_within_template 0 || loading data for generative training...
2020-11-05 09:13:00,433 INFO __main__ VS-uni-mean ball_within_template 0 || training 'generative' models...
2020-11-05 09:13:02,313 INFO root training epoch 1...
2020-11-05 09:13:22,929 INFO root collecting auccess after epoch 1...
2020-11-05 09:13:28,027 INFO root Loading cache from /media/compute/homes/aharter/.cache/phyre/offline_simulation/100000/ball
2020-11-05 09:13:29,194 ERROR __main__ Exception occured:
Traceback (most recent call last):
  File "solver.py", line 261, in <module>
    solver.train_supervised(epochs=epochs, train_mode=train_mode, test_ids = test_ids, setup=f'{eval_setup}_{fold_id}')
  File "/media/compute/homes/aharter/isy2020/phyre/flownet.py", line 1965, in train_supervised
    auccess = self.generative_auccess(test_ids, setup)
  File "/media/compute/homes/aharter/isy2020/phyre/flownet.py", line 907, in generative_auccess
    a  = sample_action_vector(ball, self.cache, uniform=self.uniform, radmode=self.radmode, mask=mask, check_border=True)
  File "/media/compute/homes/aharter/isy2020/phyre/phyre_utils.py", line 598, in sample_action_vector
    return np.array([x/wid,y/wid,rad/8])
TypeError: unsupported operand type(s) for /: 'tuple' and 'int'
2020-11-05 09:19:53,966 INFO root Loading cache from /media/compute/homes/aharter/.cache/phyre/offline_simulation/100000/ball
2020-11-05 09:19:58,313 INFO __main__ VS-uni-mean ball_within_template 0 || loading data for generative training...
2020-11-05 09:21:11,745 INFO __main__ VS-uni-mean ball_within_template 0 || training 'generative' models...
2020-11-05 09:21:13,612 INFO root training epoch 1...
2020-11-05 09:21:33,430 INFO root collecting auccess after epoch 1...
2020-11-05 09:21:38,658 INFO root Loading cache from /media/compute/homes/aharter/.cache/phyre/offline_simulation/100000/ball
2020-11-05 09:21:39,840 ERROR __main__ Exception occured:
Traceback (most recent call last):
  File "solver.py", line 261, in <module>
    solver.train_supervised(epochs=epochs, train_mode=train_mode, test_ids = test_ids, setup=f'{eval_setup}_{fold_id}')
  File "/media/compute/homes/aharter/isy2020/phyre/flownet.py", line 1965, in train_supervised
    auccess = self.generative_auccess(test_ids, setup)
  File "/media/compute/homes/aharter/isy2020/phyre/flownet.py", line 907, in generative_auccess
    a  = sample_action_vector(ball, self.cache, uniform=self.uniform, radmode=self.radmode, mask=mask, check_border=True)
  File "/media/compute/homes/aharter/isy2020/phyre/phyre_utils.py", line 598, in sample_action_vector
    return np.array([x,y,rad/8])
TypeError: unsupported operand type(s) for /: 'tuple' and 'int'
2020-11-05 10:03:13,415 INFO root Loading cache from /media/compute/homes/aharter/.cache/phyre/offline_simulation/100000/ball
2020-11-05 10:03:17,555 INFO __main__ VS-uni-mean ball_within_template 0 || loading data for generative training...
2020-11-05 10:04:31,960 INFO __main__ VS-uni-mean ball_within_template 0 || training 'generative' models...
2020-11-05 10:04:33,846 INFO root training epoch 1...
2020-11-05 10:04:53,197 INFO root collecting auccess after epoch 1...
2020-11-05 10:04:58,356 INFO root Loading cache from /media/compute/homes/aharter/.cache/phyre/offline_simulation/100000/ball
2020-11-05 10:13:47,506 INFO root finish collecting auccess after epoch 1: 0.06863040770094953
2020-11-05 10:13:47,507 INFO root training epoch 2...
2020-11-05 10:14:07,135 INFO root collecting auccess after epoch 2...
2020-11-05 10:14:12,201 INFO root Loading cache from /media/compute/homes/aharter/.cache/phyre/offline_simulation/100000/ball
2020-11-05 10:23:04,236 INFO root finish collecting auccess after epoch 2: 0.07998005725031457
2020-11-05 10:23:04,237 INFO root training epoch 3...
2020-11-05 10:23:23,571 INFO root training epoch 4...
2020-11-05 10:23:42,873 INFO root training epoch 5...
2020-11-05 10:24:02,137 INFO root collecting auccess after epoch 5...
2020-11-05 10:24:07,445 INFO root Loading cache from /media/compute/homes/aharter/.cache/phyre/offline_simulation/100000/ball
2020-11-05 10:32:58,159 INFO root finish collecting auccess after epoch 5: 0.09469252078993934
2020-11-05 10:32:58,160 INFO root training epoch 6...
2020-11-05 10:33:19,045 INFO root training epoch 7...
2020-11-05 10:33:40,385 INFO root training epoch 8...
2020-11-05 10:34:01,728 INFO root training epoch 9...
2020-11-05 10:34:23,087 INFO root training epoch 10...
2020-11-05 10:34:44,413 INFO root collecting auccess after epoch 10...
2020-11-05 10:34:49,529 INFO root Loading cache from /media/compute/homes/aharter/.cache/phyre/offline_simulation/100000/ball
2020-11-05 10:43:37,692 INFO root finish collecting auccess after epoch 10: 0.10261167462069395
2020-11-05 10:43:38,955 INFO __main__ VS-uni-mean ball_within_template 0 || saving models...
2020-11-05 10:43:39,206 INFO __main__ VS-uni-mean ball_within_template 0 || loading data for generative testing...
2020-11-05 10:43:39,668 INFO __main__ VS-uni-mean ball_within_template 0 || inspecting generative performance...
2020-11-05 10:43:44,973 INFO root Loading cache from /media/compute/homes/aharter/.cache/phyre/offline_simulation/100000/ball
2020-11-05 10:43:49,057 INFO __main__ VS-uni-mean ball_cross_template 0 || loading data for generative training...
2020-11-05 10:43:53,907 INFO __main__ VS-uni-mean ball_cross_template 0 || training 'generative' models...
2020-11-05 10:43:53,917 INFO root training epoch 1...
2020-11-05 10:44:14,163 INFO root collecting auccess after epoch 1...
2020-11-05 10:44:19,272 INFO root Loading cache from /media/compute/homes/aharter/.cache/phyre/offline_simulation/100000/ball
2020-11-05 10:52:50,701 INFO root finish collecting auccess after epoch 1: 0.04264821198718522
2020-11-05 10:52:50,702 INFO root training epoch 2...
2020-11-05 10:53:11,688 INFO root collecting auccess after epoch 2...
2020-11-05 10:53:16,955 INFO root Loading cache from /media/compute/homes/aharter/.cache/phyre/offline_simulation/100000/ball
2020-11-05 11:01:45,474 INFO root finish collecting auccess after epoch 2: 0.053863947226038426
2020-11-05 11:01:45,475 INFO root training epoch 3...
2020-11-05 11:02:06,328 INFO root training epoch 4...
2020-11-05 11:02:27,399 INFO root training epoch 5...
2020-11-05 11:02:48,413 INFO root collecting auccess after epoch 5...
2020-11-05 11:02:53,451 INFO root Loading cache from /media/compute/homes/aharter/.cache/phyre/offline_simulation/100000/ball
2020-11-05 11:11:11,342 INFO root finish collecting auccess after epoch 5: 0.07770704692143883
2020-11-05 11:11:11,343 INFO root training epoch 6...
2020-11-05 11:11:32,737 INFO root training epoch 7...
2020-11-05 11:11:54,592 INFO root training epoch 8...
2020-11-05 11:12:16,513 INFO root training epoch 9...
2020-11-05 11:12:38,394 INFO root training epoch 10...
2020-11-05 11:13:00,257 INFO root collecting auccess after epoch 10...
2020-11-05 11:13:05,481 INFO root Loading cache from /media/compute/homes/aharter/.cache/phyre/offline_simulation/100000/ball
2020-11-05 11:21:21,376 INFO root finish collecting auccess after epoch 10: 0.09353465697810522
2020-11-05 11:21:22,596 INFO __main__ VS-uni-mean ball_cross_template 0 || saving models...
2020-11-05 11:21:22,851 INFO __main__ VS-uni-mean ball_cross_template 0 || loading data for generative testing...
2020-11-05 11:21:23,094 INFO __main__ VS-uni-mean ball_cross_template 0 || inspecting generative performance...
2020-11-05 11:21:25,944 INFO __main__ ['ball_within_template', 'ball_cross_template']
